"""
U2E Evolution Engine — MCP Server

Handles all deterministic evolution bookkeeping:
population state, selection, batch planning, lineage tracking.

The agent calls these tools; the LLM handles code generation and reflection.
"""

from __future__ import annotations

import fnmatch
import hashlib
import json
import os
import subprocess
from pathlib import Path

from mcp.server.fastmcp import FastMCP

from models import (
    BatchItem,
    EvolutionConfig,
    EvolutionState,
    Individual,
    Objective,
    Operation,
    SurvivorResult,
    Target,
    TargetStatus,
)
from selection import (
    plan_generation,
    random_select,
    rank_select,
    select_survivors,
    update_temperatures,
)

mcp = FastMCP("evo-engine", instructions="U2E evolutionary algorithm bookkeeping")

# ---------------------------------------------------------------------------
# State persistence
# ---------------------------------------------------------------------------

_STATE_DIR = os.environ.get("U2E_STATE_DIR", os.path.expanduser("~/.openclaw/u2e-state"))
_state: EvolutionState | None = None


def _state_path() -> Path:
    return Path(_STATE_DIR) / "state.json"


def _save() -> None:
    if _state is None:
        return
    p = _state_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_state.model_dump_json(indent=2))


def _load() -> EvolutionState | None:
    p = _state_path()
    if p.exists():
        return EvolutionState.model_validate_json(p.read_text())
    return None


def _get_state() -> EvolutionState:
    global _state
    if _state is None:
        _state = _load()
    if _state is None:
        raise RuntimeError("Evolution not initialized. Call evo_init first.")
    return _state


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------


@mcp.tool()
def evo_init(
    repo_path: str,
    benchmark_cmd: str,
    objective: str = "min",
    max_fe: int = 500,
    pop_size: int = 8,
    mutation_rate: float = 0.5,
    synergy_interval: int = 3,
    top_k_survive: int = 5,
    quick_cmd: str = "",
) -> dict:
    """Initialize a new evolution run.

    Args:
        repo_path: Path to the target git repository.
        benchmark_cmd: Command to run for fitness evaluation.
        objective: 'min' or 'max'.
        max_fe: Maximum number of fitness evaluations.
        pop_size: Number of variants per target per generation.
        mutation_rate: Fraction of variants generated by mutation (vs crossover).
        synergy_interval: Run synergy check every N generations.
        top_k_survive: Keep top K branches per target.
        quick_cmd: Optional quick evaluation command for pre-filtering.
    """
    global _state

    config = EvolutionConfig(
        repo_path=repo_path,
        benchmark_cmd=benchmark_cmd,
        objective=Objective(objective),
        max_fe=max_fe,
        pop_size=pop_size,
        mutation_rate=mutation_rate,
        synergy_interval=synergy_interval,
        top_k_survive=top_k_survive,
        quick_cmd=quick_cmd or None,
    )

    _state = EvolutionState(config=config)
    _save()

    return {
        "status": "initialized",
        "repo_path": repo_path,
        "objective": objective,
        "max_fe": max_fe,
        "pop_size": pop_size,
    }


@mcp.tool()
def evo_register_targets(targets: list[dict]) -> dict:
    """Register optimization targets identified by code analysis.

    Args:
        targets: List of targets, each with keys:
            id, file, function, lines (optional), impact (optional), description (optional).
    """
    state = _get_state()

    for t in targets:
        target = Target(
            id=t["id"],
            file=t["file"],
            function=t["function"],
            lines=t.get("lines", ""),
            impact=t.get("impact", "medium"),
            description=t.get("description", ""),
        )
        state.targets[target.id] = target
        state.active_branches[target.id] = []

    _save()

    return {
        "registered": len(targets),
        "target_ids": [t["id"] for t in targets],
    }


@mcp.tool()
def evo_report_seed(obj: float) -> dict:
    """Report the seed baseline fitness.

    Args:
        obj: The objective value of the seed (unmodified) code.
    """
    state = _get_state()
    state.seed_obj = obj
    state.best_obj_overall = obj
    state.total_evals += 1

    for target in state.targets.values():
        target.current_best_obj = obj

    _save()

    return {"seed_obj": obj, "total_evals": state.total_evals}


@mcp.tool()
def evo_next_batch() -> dict:
    """Get the next batch of operations to execute.

    Returns a list of operations, each specifying:
    - branch: the branch name to create
    - operation: 'mutate', 'crossover', or 'synergy'
    - target_id: which target this operates on
    - parent_branches: which branch(es) to base this on
    - target_file: the file containing the target function
    - target_function: the function name to modify
    """
    state = _get_state()
    is_min = state.config.objective == Objective.MIN
    budget_remaining = state.config.max_fe - state.total_evals

    if budget_remaining <= 0:
        return {"done": True, "reason": "budget exhausted", "batch": []}

    # Plan this generation
    plan = plan_generation(
        targets=state.targets,
        pop_size=state.config.pop_size,
        mutation_rate=state.config.mutation_rate,
        budget_remaining=budget_remaining,
        synergy_interval=state.config.synergy_interval,
        generation=state.generation,
        is_minimize=is_min,
    )

    batch: list[dict] = []
    var_counter: dict[str, int] = {}

    for item in plan:
        tid = item["target_id"]
        op = item["operation"]
        count = item["count"]

        for v in range(count):
            key = f"{tid}/{op.value}"
            var_counter[key] = var_counter.get(key, 0)
            idx = var_counter[key]
            var_counter[key] += 1

            if op == Operation.SYNERGY:
                branch = f"gen-{state.generation}/synergy/{tid}-{idx}"
                # For synergy, parents are the best of each constituent target
                parts = tid.split("+")
                parents = []
                for part in parts:
                    t = state.targets.get(part)
                    if t and t.current_best_branch:
                        parents.append(t.current_best_branch)
                batch.append(BatchItem(
                    branch=branch,
                    operation=op,
                    target_id=tid,
                    parent_branches=parents,
                    target_file="",
                    target_function="",
                ).model_dump())
            else:
                target = state.targets[tid]
                branch = f"gen-{state.generation}/{tid}/{op.value}-{idx}"

                # Determine parents
                if op == Operation.CROSSOVER:
                    # Pick two parents from active branches
                    active = state.active_branches.get(tid, [])
                    active_inds = [
                        state.individuals[b] for b in active
                        if b in state.individuals and state.individuals[b].success
                    ]
                    pairs = random_select(active_inds, 1, is_minimize=is_min)
                    if pairs:
                        parents = [pairs[0][0].branch, pairs[0][1].branch]
                    elif target.current_best_branch:
                        parents = [target.current_best_branch]
                    else:
                        parents = [state.seed_branch]
                elif op == Operation.MUTATE:
                    if target.current_best_branch:
                        parents = [target.current_best_branch]
                    else:
                        parents = [state.seed_branch]
                else:
                    parents = []

                batch.append(BatchItem(
                    branch=branch,
                    operation=op,
                    target_id=tid,
                    parent_branches=parents,
                    target_file=target.file,
                    target_function=target.function,
                ).model_dump())

    return {
        "generation": state.generation,
        "budget_remaining": budget_remaining,
        "batch_size": len(batch),
        "batch": batch,
    }


@mcp.tool()
def evo_report_fitness(
    branch: str,
    target_id: str,
    operation: str,
    parent_branches: list[str],
    fitness: float,
    success: bool,
    code_hash: str = "",
    raw_output: str = "",
) -> dict:
    """Report the fitness evaluation result for a branch.

    Args:
        branch: The branch that was evaluated.
        target_id: Which target was modified.
        operation: 'mutate', 'crossover', or 'synergy'.
        parent_branches: Parent branch(es).
        fitness: The objective value.
        success: Whether the evaluation succeeded.
        code_hash: Hash of the generated code (for dedup).
        raw_output: Last lines of stdout (for debugging).
    """
    state = _get_state()
    is_min = state.config.objective == Objective.MIN

    # Check cache
    if code_hash and code_hash in state.fitness_cache:
        cached = state.fitness_cache[code_hash]
        return {
            "cached": True,
            "fitness": cached,
            "branch": branch,
        }

    ind = Individual(
        branch=branch,
        generation=state.generation,
        target_id=target_id,
        operation=Operation(operation),
        parent_branches=parent_branches,
        fitness=fitness,
        success=success,
        code_hash=code_hash,
        raw_output=raw_output[:500] if raw_output else None,
    )

    state.individuals[branch] = ind
    state.total_evals += 1

    if code_hash:
        state.fitness_cache[code_hash] = fitness

    # Update active branches
    if target_id not in state.active_branches:
        state.active_branches[target_id] = []
    if success:
        state.active_branches[target_id].append(branch)

    # Update target best
    if success and target_id in state.targets:
        target = state.targets[target_id]
        improved = False
        if target.current_best_obj is None:
            improved = True
        elif is_min and fitness < target.current_best_obj:
            improved = True
        elif not is_min and fitness > target.current_best_obj:
            improved = True

        if improved:
            target.current_best_obj = fitness
            target.current_best_branch = branch
            target.stagnation_count = 0
        # (stagnation is incremented at end of generation in select_survivors)

    # Update global best
    if success:
        if state.best_obj_overall is None:
            state.best_obj_overall = fitness
            state.best_branch_overall = branch
        elif is_min and fitness < state.best_obj_overall:
            state.best_obj_overall = fitness
            state.best_branch_overall = branch
        elif not is_min and fitness > state.best_obj_overall:
            state.best_obj_overall = fitness
            state.best_branch_overall = branch

    _save()

    return {
        "branch": branch,
        "fitness": fitness,
        "success": success,
        "total_evals": state.total_evals,
        "is_new_best": branch == state.best_branch_overall,
    }


@mcp.tool()
def evo_select_survivors() -> dict:
    """Run selection at end of generation. Returns branches to keep and eliminate.

    Also advances the generation counter and updates temperatures.
    """
    state = _get_state()
    is_min = state.config.objective == Objective.MIN

    all_keep: list[str] = []
    all_eliminate: list[str] = []
    best_branch = state.best_branch_overall or state.seed_branch
    best_obj = state.best_obj_overall

    for target_id, branches in state.active_branches.items():
        inds = [state.individuals[b] for b in branches if b in state.individuals]
        keep, elim = select_survivors(inds, state.config.top_k_survive, is_minimize=is_min)

        keep_branches = [ind.branch for ind in keep]
        elim_branches = [ind.branch for ind in elim]

        # Never eliminate the global best
        if state.best_branch_overall in elim_branches:
            elim_branches.remove(state.best_branch_overall)
            keep_branches.append(state.best_branch_overall)

        state.active_branches[target_id] = keep_branches
        all_keep.extend(keep_branches)
        all_eliminate.extend(elim_branches)

        # Update stagnation
        if target_id in state.targets:
            target = state.targets[target_id]
            # Check if this target improved this generation
            gen_inds = [
                state.individuals[b] for b in branches
                if b in state.individuals and state.individuals[b].generation == state.generation
            ]
            gen_improved = any(
                ind.success and ind.fitness is not None and ind.branch == target.current_best_branch
                for ind in gen_inds
            )
            if not gen_improved:
                target.stagnation_count += 1

    # Update temperatures
    update_temperatures(state.targets, is_minimize=is_min)

    # Advance generation
    state.generation += 1
    _save()

    return SurvivorResult(
        keep=all_keep,
        eliminate=all_eliminate,
        best_branch=best_branch,
        best_obj=best_obj,
    ).model_dump()


@mcp.tool()
def evo_get_status() -> dict:
    """Get current evolution status."""
    state = _get_state()

    target_status = {}
    for tid, target in state.targets.items():
        target_status[tid] = {
            "status": target.status.value,
            "temperature": round(target.temperature, 2),
            "current_best_obj": target.current_best_obj,
            "current_best_branch": target.current_best_branch,
            "stagnation": target.stagnation_count,
            "active_branches": len(state.active_branches.get(tid, [])),
        }

    return {
        "generation": state.generation,
        "total_evals": state.total_evals,
        "budget_remaining": state.config.max_fe - state.total_evals,
        "seed_obj": state.seed_obj,
        "best_obj_overall": state.best_obj_overall,
        "best_branch_overall": state.best_branch_overall,
        "improvement": _calc_improvement(state),
        "targets": target_status,
    }


@mcp.tool()
def evo_get_lineage(branch: str) -> dict:
    """Trace the full ancestry of a branch.

    Args:
        branch: The branch to trace.
    """
    state = _get_state()

    lineage = []
    visited = set()
    queue = [branch]

    while queue:
        b = queue.pop(0)
        if b in visited or b not in state.individuals:
            continue
        visited.add(b)
        ind = state.individuals[b]
        lineage.append({
            "branch": ind.branch,
            "generation": ind.generation,
            "target_id": ind.target_id,
            "operation": ind.operation.value,
            "parent_branches": ind.parent_branches,
            "fitness": ind.fitness,
            "success": ind.success,
        })
        queue.extend(ind.parent_branches)

    return {"branch": branch, "lineage": lineage}


@mcp.tool()
def evo_freeze_target(target_id: str) -> dict:
    """Freeze a target — stop evolving it.

    Args:
        target_id: The target to freeze.
    """
    state = _get_state()
    if target_id not in state.targets:
        return {"error": f"Target '{target_id}' not found"}
    state.targets[target_id].status = TargetStatus.FROZEN
    state.targets[target_id].temperature = 0.0
    _save()
    return {"target_id": target_id, "status": "frozen"}


@mcp.tool()
def evo_boost_target(target_id: str) -> dict:
    """Boost a target — increase its evolution priority.

    Args:
        target_id: The target to boost.
    """
    state = _get_state()
    if target_id not in state.targets:
        return {"error": f"Target '{target_id}' not found"}
    target = state.targets[target_id]
    target.status = TargetStatus.ACTIVE
    target.temperature = min(3.0, target.temperature + 1.0)
    target.stagnation_count = 0
    _save()
    return {"target_id": target_id, "temperature": target.temperature}


@mcp.tool()
def evo_record_synergy(
    branch: str,
    target_ids: list[str],
    fitness: float,
    success: bool,
    individual_fitnesses: dict[str, float] | None = None,
) -> dict:
    """Record the result of a synergy (cross-function combination) experiment.

    Args:
        branch: The synergy branch.
        target_ids: Which targets were combined.
        fitness: Combined fitness.
        success: Whether it succeeded.
        individual_fitnesses: Individual best fitnesses for comparison.
    """
    state = _get_state()

    # Calculate synergy gain
    gain = None
    if individual_fitnesses and success:
        is_min = state.config.objective == Objective.MIN
        individual_best = min(individual_fitnesses.values()) if is_min else max(individual_fitnesses.values())
        if is_min:
            gain = individual_best - fitness  # positive = synergy helps
        else:
            gain = fitness - individual_best

    record = {
        "branch": branch,
        "generation": state.generation,
        "target_ids": target_ids,
        "fitness": fitness,
        "success": success,
        "individual_fitnesses": individual_fitnesses,
        "synergy_gain": gain,
    }
    state.synergy_records.append(record)
    _save()

    return record


@mcp.tool()
def evo_check_cache(code_hash: str) -> dict:
    """Check if a code variant was already evaluated.

    Args:
        code_hash: Hash of the normalized code.
    """
    state = _get_state()
    if code_hash in state.fitness_cache:
        return {"cached": True, "fitness": state.fitness_cache[code_hash]}
    return {"cached": False}


# ---------------------------------------------------------------------------
# evo_step — stateless loop driver
# ---------------------------------------------------------------------------

# Phase constants (passed as strings so they are readable in LLM output)
_PHASE_BEGIN   = "begin_generation"   # start a new generation
_PHASE_CODE    = "code_ready"         # LLM committed code for a branch
_PHASE_FITNESS = "fitness_ready"      # LLM ran benchmark, has fitness value
_PHASE_SELECT  = "select"             # all items evaluated, run selection
_PHASE_REFLECT = "reflect_done"       # LLM finished writing memory
_PHASE_DONE    = "done"               # budget exhausted


def _policy_check(repo_path: str, branch: str, parent: str,
                  protected_patterns: list[str],
                  allowed_files: set[str]) -> tuple[bool, str]:
    """Run git diff and check for policy violations.

    Returns (approved: bool, reason: str).
    """
    result = subprocess.run(
        ["git", "-C", repo_path, "diff", "--name-only", f"{parent}..{branch}"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return False, f"git diff failed: {result.stderr.strip()}"

    changed = [f for f in result.stdout.strip().splitlines() if f]
    for f in changed:
        basename = os.path.basename(f)
        for pat in protected_patterns:
            if fnmatch.fnmatch(f, pat) or fnmatch.fnmatch(basename, pat):
                return False, f"Protected file modified: {f!r} (pattern {pat!r})"
        if allowed_files and f not in allowed_files:
            return False, f"File outside optimization targets: {f!r}"
    return True, ""


@mcp.tool()
def evo_step(phase: str, branch: str = "", parent_commit: str = "",
             fitness: float = 0.0, success: bool = True,
             operation: str = "", target_id: str = "",
             parent_branches: list[str] | None = None,
             code_hash: str = "", raw_output: str = "") -> dict:
    """Stateless evolution loop driver.

    Call this in a loop; each call returns the next action to perform and
    a cursor describing where you are.  The LLM decides whether to continue.

    Phases and what to pass:
      "begin_generation"  — start (or resume) a generation; no extra args needed.
      "code_ready"        — you committed code for `branch` (from a parent at
                            `parent_commit`).  Server runs policy check and
                            returns either action="run_benchmark" or
                            action="skip" (policy violation, already recorded).
      "fitness_ready"     — you ran the benchmark for `branch`; pass fitness /
                            success / operation / target_id / parent_branches.
                            Server records the result and returns the next item
                            to generate, or action="select" when the batch is done.
      "select"            — trigger survivor selection (call after batch is done).
      "reflect_done"      — you finished writing memory; server checks budget and
                            returns action="begin_generation" or action="done".
    """
    state = _get_state()
    pb = parent_branches or []

    # ------------------------------------------------------------------ begin
    if phase == _PHASE_BEGIN:
        budget_remaining = state.config.max_fe - state.total_evals
        if budget_remaining <= 0:
            return {"action": _PHASE_DONE, "reason": "budget exhausted",
                    "total_evals": state.total_evals}

        is_min = state.config.objective == Objective.MIN
        plan = plan_generation(
            targets=state.targets,
            pop_size=state.config.pop_size,
            mutation_rate=state.config.mutation_rate,
            budget_remaining=budget_remaining,
            synergy_interval=state.config.synergy_interval,
            generation=state.generation,
            is_minimize=is_min,
        )

        # Build batch items (same logic as evo_next_batch)
        batch: list[BatchItem] = []
        var_counter: dict[str, int] = {}
        for item in plan:
            tid = item["target_id"]
            op = item["operation"]
            count = item["count"]
            for v in range(count):
                key = f"{tid}/{op.value}"
                var_counter[key] = var_counter.get(key, 0)
                idx = var_counter[key]
                var_counter[key] += 1
                if op == Operation.SYNERGY:
                    b = f"gen-{state.generation}/synergy/{tid}-{idx}"
                    parts = tid.split("+")
                    parents_list = [
                        state.targets[p].current_best_branch
                        for p in parts
                        if p in state.targets and state.targets[p].current_best_branch
                    ]
                    batch.append(BatchItem(branch=b, operation=op, target_id=tid,
                                           parent_branches=parents_list,
                                           target_file="", target_function=""))
                else:
                    target = state.targets[tid]
                    b = f"gen-{state.generation}/{tid}/{op.value}-{idx}"
                    if op == Operation.CROSSOVER:
                        active = state.active_branches.get(tid, [])
                        active_inds = [
                            state.individuals[br] for br in active
                            if br in state.individuals and state.individuals[br].success
                        ]
                        pairs = random_select(active_inds, 1, is_minimize=is_min)
                        if pairs:
                            parents_list = [pairs[0][0].branch, pairs[0][1].branch]
                        elif target.current_best_branch:
                            parents_list = [target.current_best_branch]
                        else:
                            parents_list = [state.seed_branch]
                    else:
                        parents_list = (
                            [target.current_best_branch] if target.current_best_branch
                            else [state.seed_branch]
                        )
                    batch.append(BatchItem(branch=b, operation=op, target_id=tid,
                                           parent_branches=parents_list,
                                           target_file=target.file,
                                           target_function=target.function))

        state.current_batch = batch
        state.batch_cursor = 0
        _save()

        if not batch:
            return {"action": _PHASE_DONE, "reason": "empty batch", "total_evals": state.total_evals}

        first = batch[0]
        return {
            "action": "generate_code",
            "generation": state.generation,
            "batch_size": len(batch),
            "cursor": 0,
            "item": first.model_dump(),
        }

    # ------------------------------------------------------------------ code_ready
    if phase == _PHASE_CODE:
        if not branch:
            return {"error": "branch is required for phase 'code_ready'"}

        # Find the batch item for this branch to get allowed files
        item = next((it for it in state.current_batch if it.branch == branch), None)
        allowed: set[str] = set()
        if item and item.target_file:
            allowed = {item.target_file}

        # Parent: use provided parent_commit, fall back to parent_branches[0]
        parent = parent_commit
        if not parent and item and item.parent_branches:
            # resolve branch name to commit hash
            r = subprocess.run(
                ["git", "-C", state.config.repo_path, "rev-parse", item.parent_branches[0]],
                capture_output=True, text=True,
            )
            parent = r.stdout.strip() if r.returncode == 0 else item.parent_branches[0]
        if not parent:
            return {"error": "Cannot determine parent commit for policy check. "
                             "Pass parent_commit= explicitly."}

        approved, reason = _policy_check(
            repo_path=state.config.repo_path,
            branch=branch,
            parent=parent,
            protected_patterns=state.config.protected_patterns,
            allowed_files=allowed,
        )

        if not approved:
            # Record as policy violation without counting as a real eval
            ind = Individual(
                branch=branch,
                generation=state.generation,
                target_id=item.target_id if item else "",
                operation=item.operation if item else Operation.MUTATE,
                parent_branches=item.parent_branches if item else [],
                fitness=None,
                success=False,
                raw_output=f"policy_violation: {reason}",
            )
            state.individuals[branch] = ind
            state.batch_cursor += 1
            _save()
            next_step = _next_item_or_select(state)
            next_step["policy_violation"] = {"branch": branch, "reason": reason}
            return next_step

        # Approved — tell LLM to run the benchmark
        return {
            "action": "run_benchmark",
            "branch": branch,
            "approved": True,
        }

    # ------------------------------------------------------------------ fitness_ready
    if phase == _PHASE_FITNESS:
        is_min = state.config.objective == Objective.MIN
        ind = Individual(
            branch=branch,
            generation=state.generation,
            target_id=target_id,
            operation=Operation(operation) if operation else Operation.MUTATE,
            parent_branches=pb,
            fitness=fitness,
            success=success,
            code_hash=code_hash,
            raw_output=raw_output[:500] if raw_output else None,
        )
        state.individuals[branch] = ind
        state.total_evals += 1

        if code_hash:
            state.fitness_cache[code_hash] = fitness

        if target_id not in state.active_branches:
            state.active_branches[target_id] = []
        if success:
            state.active_branches[target_id].append(branch)

        # Update target best
        if success and target_id in state.targets:
            target = state.targets[target_id]
            improved = (
                target.current_best_obj is None
                or (is_min and fitness < target.current_best_obj)
                or (not is_min and fitness > target.current_best_obj)
            )
            if improved:
                target.current_best_obj = fitness
                target.current_best_branch = branch
                target.stagnation_count = 0

        # Update global best
        if success:
            if state.best_obj_overall is None:
                state.best_obj_overall = fitness
                state.best_branch_overall = branch
            elif is_min and fitness < state.best_obj_overall:
                state.best_obj_overall = fitness
                state.best_branch_overall = branch
            elif not is_min and fitness > state.best_obj_overall:
                state.best_obj_overall = fitness
                state.best_branch_overall = branch

        state.batch_cursor += 1
        _save()
        result = _next_item_or_select(state)
        result["recorded_fitness"] = fitness
        result["is_new_best"] = branch == state.best_branch_overall
        return result

    # ------------------------------------------------------------------ select
    if phase == _PHASE_SELECT:
        result = evo_select_survivors()
        result["action"] = "reflect"
        return result

    # ------------------------------------------------------------------ reflect_done
    if phase == _PHASE_REFLECT:
        budget_remaining = state.config.max_fe - state.total_evals
        if budget_remaining <= 0:
            return {"action": _PHASE_DONE, "reason": "budget exhausted",
                    "total_evals": state.total_evals, "best_obj": state.best_obj_overall}
        return {"action": _PHASE_BEGIN, "budget_remaining": budget_remaining,
                "generation": state.generation}

    return {"error": f"Unknown phase: {phase!r}. Valid phases: "
            f"{_PHASE_BEGIN}, {_PHASE_CODE}, {_PHASE_FITNESS}, {_PHASE_SELECT}, {_PHASE_REFLECT}"}


def _next_item_or_select(state: EvolutionState) -> dict:
    """Return next generate_code action or trigger select if batch is done."""
    if state.batch_cursor < len(state.current_batch):
        item = state.current_batch[state.batch_cursor]
        return {
            "action": "generate_code",
            "generation": state.generation,
            "cursor": state.batch_cursor,
            "batch_size": len(state.current_batch),
            "item": item.model_dump(),
        }
    return {
        "action": "select",
        "generation": state.generation,
        "items_evaluated": len(state.current_batch),
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _calc_improvement(state: EvolutionState) -> str | None:
    if state.seed_obj is None or state.best_obj_overall is None:
        return None
    if state.seed_obj == 0:
        return None
    pct = (state.best_obj_overall - state.seed_obj) / abs(state.seed_obj) * 100
    return f"{pct:+.1f}%"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
